<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE afiliados [
    <!ELEMENT afiliados (afiliado+)>
    <!ELEMENT afiliado ((DNI | NIE), nombre, apellidos, situacion_laboral, fecha_nacimiento, bajas?, prestaciones_cobradas?)>
    <!ELEMENT DNI (#PCDATA)>
    <!ELEMENT NIE (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT situacion_laboral (#PCDATA)>
    <!ELEMENT fecha_nacimiento (dia, mes, año)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT bajas (baja*)>
    <!ELEMENT baja (causa, fecha_inicio_baja, fecha_final_baja?)>
    <!ELEMENT causa (#PCDATA)>
    <!ELEMENT fecha_inicio_baja (#PCDATA)>
    <!ELEMENT fecha_final_baja (#PCDATA)>
    <!ELEMENT prestaciones_cobradas (prestacion*)>
    <!ELEMENT prestacion (cantidad, fecha_inicio_prestacion, fecha_final_prestacion)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT fecha_inicio_prestacion (#PCDATA)>
    <!ELEMENT fecha_final_prestacion (#PCDATA)>
]>

<afiliados>
    <afiliado>
        <DNI>12345678A</DNI>
        <nombre>Juan</nombre>
        <apellidos>García López</apellidos>
        <situacion_laboral>en_activo</situacion_laboral>
        <fecha_nacimiento>
            <dia>15</dia>
            <mes>03</mes>
            <año>1985</año>
        </fecha_nacimiento>
        <bajas>
            <baja>
                <causa>Enfermedad</causa>
                <fecha_inicio_baja>2024-05-01</fecha_inicio_baja>
                <fecha_final_baja>2024-05-15</fecha_final_baja>
            </baja>
            <baja>
                <causa>Vacaciones</causa>
                <fecha_inicio_baja>2024-07-01</fecha_inicio_baja>
                <fecha_final_baja>2024-07-15</fecha_final_baja>
            </baja>
        </bajas>
        <prestaciones_cobradas>
            <prestacion>
                <cantidad>1000</cantidad>
                <fecha_inicio_prestacion>2024-01-01</fecha_inicio_prestacion>
                <fecha_final_prestacion>2024-02-01</fecha_final_prestacion>
            </prestacion>
        </prestaciones_cobradas>
    </afiliado>
    <afiliado>
        <NIE>X1234567Y</NIE>
        <nombre>María</nombre>
        <apellidos>Álvarez Pérez</apellidos>
        <situacion_laboral>jubilado</situacion_laboral>
        <fecha_nacimiento>
            <dia>25</dia>
            <mes>08</mes>
            <año>1950</año>
        </fecha_nacimiento>
        <prestaciones_cobradas>
            <prestacion>
                <cantidad>1200</cantidad>
                <fecha_inicio_prestacion>2023-10-01</fecha_inicio_prestacion>
                <fecha_final_prestacion>2024-02-01</fecha_final_prestacion>
            </prestacion>
            <prestacion>
                <cantidad>1100</cantidad>
                <fecha_inicio_prestacion>2024-03-01</fecha_inicio_prestacion>
                <fecha_final_prestacion>2024-04-01</fecha_final_prestacion>
            </prestacion>
        </prestaciones_cobradas>
    </afiliado>
</afiliados>
